// ==============================================================================
// RULE DEFAULTS
// Built-in Tier 1 defaults for all 25 rules.
// ==============================================================================

/**
 * Sensible defaults for all built-in rules (Tier 1 in three-tier merge).
 *
 * @type {Readonly<Record<string, Record<string, unknown>>>}
 */
export const RULE_DEFAULTS: Readonly<Record<string, Record<string, unknown>>> = {
  Email: {
    length: { max: 254 },
    blockPlusAlias: false,
    blockDomains: [],
    allowDomains: [],
    blockDisposable: false,
    allowSubdomains: true,
    emptyToUndefined: true,
    normalize: true,
  },
  PersonName: {
    length: { min: 2, max: 50 },
    words: { max: 5 },
    allowUnicode: true,
    boundary: 'alpha',
    consecutive: { max: 3 },
    titleCase: false,
    emptyToUndefined: true,
    normalize: true,
  },
  BusinessName: {
    length: { min: 2, max: 100 },
    boundary: 'alphanumeric',
    consecutive: { max: 4 },
    titleCase: false,
    emptyToUndefined: true,
    normalize: true,
  },
  Password: {
    length: { min: 8, max: 128 },
    uppercase: { min: 1 },
    lowercase: { min: 1 },
    digits: { min: 1 },
    special: { min: 1 },
    consecutive: { max: 3 },
    blockCommon: false,
    emptyToUndefined: true,
    normalize: false,
  },
  PasswordConfirmation: {
    passwordField: 'password',
    emptyToUndefined: true,
    normalize: false,
  },
  Phone: {
    metadata: 'min',
    allowCountries: [],
    blockCountries: [],
    requireMobile: false,
    requireCountryCode: false,
    format: 'e164',
    emptyToUndefined: true,
    normalize: true,
  },
  Website: {
    length: { max: 255 },
    requireWww: false,
    requireHttps: false,
    allowDomains: [],
    blockDomains: [],
    allowSubdomains: true,
    allowPath: true,
    allowQuery: false,
    emptyToUndefined: true,
    normalize: true,
  },
  URL: {
    protocols: ['http', 'https'],
    requireTLD: true,
    length: { max: 2048 },
    allowDomains: [],
    blockDomains: [],
    allowQuery: true,
    allowAuth: false,
    emptyToUndefined: true,
    normalize: true,
  },
  Username: {
    length: { min: 3, max: 20 },
    pattern: 'alphanumeric-underscore',
    boundary: 'alphanumeric',
    reservedWords: [],
    blockReserved: false,
    ignoreCase: true,
    emptyToUndefined: true,
    normalize: true,
  },
  Slug: {
    length: { min: 3, max: 100 },
    emptyToUndefined: true,
    normalize: true,
  },
  PostalCode: {
    emptyToUndefined: true,
    normalize: true,
  },
  LicenseKey: {
    type: 'custom',
    segments: 5,
    segmentLength: 5,
    separator: '-',
    charset: 'alphanumeric',
    emptyToUndefined: true,
    normalize: true,
  },
  UUID: {
    version: 'any',
    emptyToUndefined: true,
    normalize: true,
  },
  JWT: {
    requireExpiry: false,
    checkExpiry: false,
    checkNotBefore: false,
    clockTolerance: 0,
    emptyToUndefined: true,
    normalize: true,
  },
  DateTime: {
    format: 'iso',
    allowFuture: true,
    allowPast: true,
    allowOffset: true,
    allowLocal: false,
    emptyToUndefined: true,
    normalize: true,
  },
  Token: {
    emptyToUndefined: true,
    normalize: true,
  },
  Text: {
    noEmails: false,
    noUrls: false,
    noPhoneNumbers: false,
    noHtml: false,
    emptyToUndefined: true,
    normalize: true,
  },
  Country: {
    format: 'alpha2',
    allowCountries: [],
    blockCountries: [],
    emptyToUndefined: true,
    normalize: true,
  },
  Currency: {
    allowCurrencies: [],
    blockCurrencies: [],
    emptyToUndefined: true,
    normalize: true,
  },
  Color: {
    format: 'hex',
    alpha: true,
    emptyToUndefined: true,
    normalize: true,
  },
  CreditCard: {
    emptyToUndefined: true,
    normalize: true,
  },
  IBAN: {
    allowCountries: [],
    blockCountries: [],
    emptyToUndefined: true,
    normalize: true,
  },
  VatNumber: {
    requirePrefix: false,
    emptyToUndefined: true,
    normalize: true,
  },
  MacAddress: {
    delimiter: ':',
    emptyToUndefined: true,
    normalize: true,
  },
  IpAddress: {
    version: 'any',
    allowCidr: false,
    allowPrivate: true,
    emptyToUndefined: true,
    normalize: true,
  },
}
